version: '3'

services: 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - minharede

  app:
    build:
      context: node
    container_name: app
    ports: 
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - minharede
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
       - db

networks: 
  minharede:
    driver: bridge
    